server/resource/controller.js, server/resource/index.js, server/util/base-sql.js
=> Add support for basic CRUD operations to Controller

server/resource/controller.js
=> Add logging to Controller

server/resource/controller.js, server/util/log.js
=> Add resource serializer

.eslintrc, example/clean-up.js, example/index.js, gulpfile.js, lib/resource-transform/index.js, lib/resource-transform/util/build-initial-migration.js, lib/resource-transform/util/generate-validations.js, lib/resource-transform/util/normalize-attributes.js, lib/resource-transform/util/require-id-validation.js, lib/resource-transform/util/types-to-formats-map.js, lib/resource-transform/util/uniquely-identify-validation.js, package.json, server/api.js, server/app.js, server/resource/routes.js, server/util/default-validations.js, server/util/json-api-headers.js, server/util/json-api-media-type.js, server/util/load-resource-configs.js, server/util/log.js, test/.eslintrc, test/globals.json, test/setup.js
Resolves #6
---
This also fixes linting errors, and begins scaffolding out the testing infrastructure.
=> Add linting

README.md, bin/commands/migrate.js, bin/commands/start.js, bin/pls.js, server/app.js
=> Cli improvements

README.md, bin/commands/migrate.js, bin/commands/reset-database.js, bin/commands/start.js, bin/pls.js, bin/util/log.js
=> Add support for verbose and silent CLI modes

bin/commands/migrate.js, package.json, server/api.js, server/resource/controller.js, server/util/adjust-resource-quantity.js, util/build-migrations/index.js, util/normalize-model/index.js, util/normalize-model/util/normalize-fields.js, util/normalize-model/util/normalize-relations.js, util/resource-dependency-graph/index.js
Still a work-in-progress, but this lets you create the relationships and CRUD them.
Some things need to be changed/updated:
- ~~"type" should be plural in GET responses~~
- ~~the resource model relationships need to be normalized~~
- the existence of type should be validated on the server when an update is sent
and probably more. but this is a good start.
---
I'm going to hold off on validating the request until later. It can be added to the JSON Schema for the resource.
=> Add support for many-to-one relationships

bin/commands/migrate.js, bin/commands/reset-database.js
=> More robust CLI errors for migration

server/resource/controller.js, server/util/base-sql.js, util/normalize-model/index.js, util/normalize-model/util/normalize-pagination.js
=> Support pagination

server/resource/controller.js, server/resource/routes.js, server/util/server-errors.js
This also fixes the errors sent when a restricted action is
attempted on a resource
Resolves #88 , at least for the primary resource.
=> Add support for sparse fields on primary resource

bin/commands/migrate.js, server/api.js, util/load-resource-models/index.js, util/validate-resource-model/index.js, util/validate-resource-model/util/resource-model-schema.json
Resolves #66
This formalizes the resource model definition file. If there are errors, then the user will learn about them before we try to do anything with them.
=> Validate resource models

util/build-migrations/index.js
This begins sanitizing the output of `migrate.js`. For the remaining values (default value and type), I'll need to either restrict it via an ENUM somehow, or create a map (similar to an ORM layer) for each property. For now, arbitrary SQL commands are allowed.
=> Begin sanitizing model migrations

test/unit/util/validate-resource-model.js
Some of the internals I'm hesitant to unit test, because of how drastically things are changing between features. But this is the entry point to the system, and it's unlikely to change drastically. It's also pretty important that the validation works properly, so here we are with some tests.
=> Add tests for resource model validation

.travis.yml, database/config.js, database/index.js, gulpfile.js, package.json, server/api.js, server/util/json-api-headers.js, test/fixtures/one-resource/person.yaml, test/helpers/README.md, test/helpers/diff-error.js, test/helpers/json-api-schema.json, test/helpers/json-api-validators.js, test/helpers/wipe-db.js, test/integration/root/index.js, test/integration/setup.js, util/load-resource-models/index.js
As part of #7 
---
This PR does two things:
1. sets up integration test infrastructure
2. adds tests for the root route
=> Add integration tests

lib/build-json-schema/index.js, lib/build-json-schema/util/uniquely-identify-validation.js, server/resource/controller.js, server/util/server-errors.js, test/fixtures/kitchen-sink/no-pagination.yaml, test/helpers/apply-migrations.js, test/helpers/json-api-validators.js, test/integration/post-resource/index.js, test/integration/root/index.js, test/setup.js
This doesn't finish tests for POSTing. There are two sorts of things left to test:
1. creating with relationships included
2. postgres errors
Presumably, if I can find a situation where I'd find 2, I'd immediately write a better response for it...so. Maybe that's untestable? I'll have to think more about it.
=> More work on tests

gulpfile.js, test/helpers/seed.js, test/unit/lib/load-resource-models.js
=> Ensure tests are linted

lib/build-json-schema/index.js, server/resource/controller.js, test/fixtures/kitchen-sink/has-meta.yaml, test/fixtures/kitchen-sink/no-meta.yaml, test/integration/patch-resource/index.js
This does not cover:
- PATCHing a relationship
- db errors
but I believe that it covers every other supported situation.
=> Add tests for PATCH

test/integration/get-many-resource/index.js, test/integration/get-one-resource/index.js
Adds some basic GET integration tests. I still need to test pagination.
=> Add some GET tests

server/resource/controller.js, server/util/build-response-relationships.js, server/util/handle-query-error.js, test/fixtures/kitchen-sink/relation.yaml, test/integration/post-resource/index.js, test/integration/root/index.js, test/unit/server/util/adjust-resource-quantity.js
=> More tests

lib/build-json-schema/index.js, package.json, server/util/handle-query-error.js, test/fixtures/kitchen-sink/relation.yaml, test/integration/get-many-resource/index.js, test/integration/get-one-resource/index.js, test/integration/patch-resource/index.js, test/integration/post-resource/index.js, test/unit/server/util/handle-query-error.js
This is part of #124. Many-to-one tests and a pretty bad unit test suite.
=> Even more tests

server/api.js, server/resource/controller.js, server/resource/routes.js, server/util/json-api-headers.js, server/util/validator.js
=> Add more logs to the server

README.md, index.js
=> Add a programmatic interface

lib/load-resource-models/index.js, test/fixtures/kitchen-sink/no-crud.json, test/fixtures/kitchen-sink/no-crud.yaml
=> Add support for JSON Resource Model files

lib/normalize-model/index.js, lib/normalize-model/util/normalize-pagination.js, lib/validate-resource-model/util/resource-model-schema.json, server/resource/middleware/read.js, server/resource/routes.js, test/fixtures/kitchen-sink/no-crud.json, test/fixtures/kitchen-sink/paginate.yaml, test/fixtures/one-resource/person.yaml, test/integration/root/index.js, test/unit/lib/normalize-model.js, test/unit/lib/validate-resource-model.js
=> Update Resource Model to use consistent casing

lib/build-json-schema/index.js, lib/build-json-schema/util/require-id-validation.js, lib/build-json-schema/util/uniquely-identify-validation.js, lib/validate-resource-model/index.js, lib/validate-resource-model/util/resource-model-schema.json, package.json, server/util/bad-request-map.js, server/util/validator.js, test/helpers/json-api-validators.js, test/integration/patch-resource/index.js, test/integration/post-resource/index.js, test/unit/server/util/bad-request-map.js
This is to support validating that the ID in the request body matches what's in the params.
Resolves #11
=> Switch from is-my-json-valid to ajv

server/api.js, server/resource/middleware/create.js, server/resource/middleware/read.js, server/resource/middleware/update.js, server/resource/routes.js, server/util/handle-query-error.js, server/util/validator.js, test/helpers/json-api-schema.json, test/integration/get-many-resource/index.js, test/integration/get-one-resource/index.js, test/integration/patch-resource/index.js, test/integration/post-resource/index.js
As part of #13 
----
This adds self-links to the top-level links object. Other links to consider:
- resource links (which can only be self)
- related links
are there other links?
=> Add self links

lib/normalize-model/util/normalize-relations.js, server/resource/controller.js, server/resource/index.js, server/resource/middleware/create.js, server/resource/middleware/read.js, server/resource/middleware/update.js, server/util/build-response-relationships.js, server/util/format-transaction.js, test/integration/get-many-resource/index.js, test/integration/get-one-resource/index.js, test/integration/patch-resource/index.js, test/integration/post-resource/index.js, test/unit/lib/normalize-model.js
Also adds links to relationship objects. Resolves #126 
---
This is a big step forward, but it also introduces a lie to api-pls. The `self` links in relationships don't work! I'll add that soon.
=> Add support for optional many-to-one relationships

server/api.js, test/integration/root/index.js
=> Update root route links object to use proper format

lib/normalize-model/index.js, lib/normalize-model/util/normalize-relationships.js, lib/sync/util/build-single-migration.js, lib/sync/util/resource-dependency-graph.js, lib/validate-resource-model/util/resource-model-schema.json, server/resource/middleware/create.js, server/resource/middleware/update.js, server/util/build-response-relationships.js, test/fixtures/kitchen-sink/has-meta.yaml, test/fixtures/kitchen-sink/no-meta.yaml, test/fixtures/kitchen-sink/no-pagination.yaml, test/fixtures/kitchen-sink/paginate.yaml, test/fixtures/kitchen-sink/relation.yaml, test/fixtures/one-resource/person.yaml, test/unit/lib/migrations/util/resource-dependency-graph.js, test/unit/lib/normalize-model.js, test/unit/lib/validate-resource-model.js
built_in_meta_attributes is now built_in_meta
relations is now relationships
Resolves #151
=> Rename properties in Resource Model

README.md, bin/pls.js, index.js, server/api.js, test/integration/delete-resource/index.js, test/integration/get-many-resource/index.js, test/integration/get-one-resource/index.js, test/integration/patch-resource/index.js, test/integration/post-resource/index.js, test/integration/root/index.js
=> Add apiVersion option

server/api.js, test/integration/root/index.js
=> Update root route meta to be "supported_actions"

package.json, server/resource/middleware/create.js, server/resource/middleware/delete.js, server/resource/middleware/read.js, server/resource/middleware/update.js, server/util/log.js
- Logs no longer send duplicate information
- New logs at the beginning of CRUD action processing
- Updates req serializer to pull out the ID of the request
Resolves #165
=> Updates to logging

README.md, bin/commands/reset-database.js, bin/commands/start.js, bin/commands/sync.js, bin/pls.js, bin/util/log.js, index.js, server/index.js
Also forwards along silent/verbose options to the app
=> Refactor CLI logging to use Pino

bin/commands/sync.js, lib/load-resource-models/index.js, lib/sync/util/build.js, package.json
=> Supply more information when "pls sync" fails

server/resource/middleware/read.js, test/integration/get-many-resource/index.js
Resolves #94 
Also added a wiki page around this behavior: https://github.com/jmeas/api-pls/wiki/Pagination-Links
=> Return correct results when no results returned from read many

lib/build-json-schema/index.js, test/fixtures/kitchen-sink/required-meta.yaml, test/fixtures/kitchen-sink/required.yaml, test/integration/patch-resource/failure.js, test/integration/patch-resource/success.js, test/integration/post-resource/failure.js, test/integration/post-resource/success.js, test/setup.js
Also updates the schema around creating and posting resources
to be more strict, and therefore, more accurate.
As part of #124
=> Add more tests around creating and updating

server/resource/middleware/create.js, test/integration/post-resource/success.js
Resolves #182
I need to add tests for this
=> Return Location header on create

lib/fill-relationships/index.js, lib/fill-relationships/util/relationship-inverse.js, lib/normalize-model/util/normalize-relationships.js, lib/sync/util/build-single-migration.js, lib/sync/util/build.js, lib/sync/util/resource-dependency-graph.js, lib/validate-resource-model/util/resource-model-schema.json, test/unit/lib/migrations/util/resource-dependency-graph.js, test/unit/lib/normalize-model.js, test/unit/lib/validate-resource-model.js
In #190, I began supporting two-way relationships. I also began realizing that I should refactor how I work with the Resource Models before I go any further.
I'm going to land this first commit from that PR, since it's easy to go in. Then, I'll see if that 2nd commit is possible to land before the refactoring as well. If not, I may need to wait.
=> Update resource models to support non-host relationships

lib/resource-definition/generate.js, lib/sql/relationship-util.js, lib/sql/sql-util.js, lib/sync/util/build-single-migration.js, lib/sync/util/build.js, server/api.js, server/resource/controller.js, server/resource/index.js, server/resource/middleware/create.js, server/resource/middleware/delete.js, server/resource/middleware/read.js, server/resource/middleware/update.js, server/resource/routes.js, server/util/build-response-relationships.js, server/util/format-transaction.js, server/util/handle-query-error.js, server/util/log.js, test/unit/server/util/handle-query-error.js
Resource Models are great for human input, but I've known for awhile now that I've needed to do more transforming of them before they'd be as useful as they could be for the controller. I've been doing quite a bit of data manipulation in my route handlers that should be computed and cached at startup. That's what this PR begins to do: introducing real Resource Definitions.
There's a lot more to do. Validation computations should be moved to the Definition file, for instance. I also need to update the logger to handle the definition. And probably some code cleanup is in order. But this is a good start!
=> Begin adding actual resource definitions

lib/resource-definition/generate.js, lib/sql/build-single-migration.js, lib/sql/many-to-many-util.js, lib/sql/sql-util.js, test/fixtures/kitchen-sink/many-to-many.yaml, test/unit/lib/sql/many-to-many-util.js
=> Create associative tables in database for many-to-many relationships

lib/sql/crud.js, lib/sql/sql-util.js, server/resource/middleware/read.js, server/resource/middleware/update.js, server/util/build-response-relationships.js, test/integration/get-many-resource/many-to-one/guest.js, test/integration/get-many-resource/one-to-one/guest.js, test/integration/get-many-resource/one-to-one/host.js, test/integration/get-one-resource/many-to-one/guest.js
As part of #201. This makes it so reads work for 4/6 relationship "situations". Next up is many-to-many reads.
=> Namespaced

.eslintrc, .travis.yml, test/integration/delete-resource/failure.js, test/integration/delete-resource/success.js, test/integration/get-many-resource/failure.js, test/integration/get-many-resource/many-to-many/guest.js, test/integration/get-many-resource/many-to-many/host.js, test/integration/get-many-resource/many-to-one/guest.js, test/integration/get-many-resource/many-to-one/host.js, test/integration/get-many-resource/one-to-one/guest.js, test/integration/get-many-resource/one-to-one/host.js, test/integration/get-many-resource/success.js, test/integration/get-one-resource/failure.js, test/integration/get-one-resource/many-to-many/guest.js, test/integration/get-one-resource/many-to-many/host.js, test/integration/get-one-resource/many-to-one/guest.js, test/integration/get-one-resource/many-to-one/host.js, test/integration/get-one-resource/one-to-one/guest.js, test/integration/get-one-resource/one-to-one/host.js, test/integration/get-one-resource/success.js, test/integration/patch-resource/failure.js, test/integration/patch-resource/many-to-one/host.js, test/integration/patch-resource/success.js, test/integration/post-resource/failure.js, test/integration/post-resource/many-to-one/host.js, test/integration/post-resource/one-to-one/host.js, test/integration/post-resource/success.js, test/integration/root/index.js
=> Update to use Node 7.6

.babelrc, gulpfile.js, package.json, server/resource/middleware/create.js, server/resource/middleware/delete.js, server/resource/middleware/read.js, server/resource/middleware/update.js
For the writes, this doesn't make the code much cleaner. But it begins the process of making the read middleware much nicer.
I'll need to go back through to tidy things up further, but I see a good path forward here.
=> Async await middlewares

lib/resource-definition/generate.js, lib/resource-model/non-serializable-fields.json, lib/resource-model/normalize/index.js, lib/sql/crud.js, server/resource/middleware/read.js, test/fixtures/authorization/transaction.js, test/integration/authorization/additional_condition.js
Resolves #232
Note that this only works for the primary resource. If a linked resource has another owner, then it will be returned. Prolly not ideal, but I'll follow up with a fix for that.
=> Add support for additional_condition

CHANGELOG.md, README.md, bin/commands/reset-database.js, bin/commands/sync.js, bin/pls.js, package.json
=> Add support for --force flag to enable scripted usage of API
